name: MyPet-Eggs
main: de.Keyle.MyPet.Eggs.MyPetEggsPlugin
version: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
author: Keyle
website: ${project.url}
depend: [MyPet]
loadbefore: [TimTheEnchanter]
